# backend/app/api/routes/ai.py
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from app.services.llm import llm_service

router = APIRouter(prefix="/ai", tags=["AI Integration"])

# Input snapshot schema
class TaskSnapshot(BaseModel):
    id: Optional[str] = None
    title: str
    description: Optional[str] = None
    status: str
    priority: str
    due_date: Optional[str] = None
    assignee_id: Optional[str] = None

class ProjectSnapshotRequest(BaseModel):
    project_name: str = Field(..., description="The name of the project")
    project_description: Optional[str] = Field(None, description="The description of the project")
    tasks: List[TaskSnapshot] = Field(default=[], description="List of tasks in the project")

# Output schema
class InsightResponse(BaseModel):
    content: str = Field(..., description="The Markdown format insight report generated by AI")
    model: str = Field(..., description="The model used to generate the report")
    is_demo: bool = Field(..., description="Indicates if the system ran in Demo Mode")

@router.post("/insights", response_model=InsightResponse)
async def generate_project_insights(payload: ProjectSnapshotRequest):
    try:
        # Convert task list of Pydantic models back to primitive dicts for processing
        task_dicts = [task.model_dump() for task in payload.tasks]
        
        result = await llm_service.get_insights(
            project_name=payload.project_name,
            project_description=payload.project_description or "",
            tasks=task_dicts
        )
        return InsightResponse(
            content=result["content"],
            model=result["model"],
            is_demo=result["is_demo"]
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to generate project insights: {str(e)}")
